layout_spectrum: 1
color:
  saturation: 0.1272401
  brandStrength: 0.178772
  lightness: 0.9749104
  rhythmicContrast: 0.1899642
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.4032258
name: Kyria
